import { DashboardColumn } from '@/app/dashboard/columns';

const data: DashboardColumn[] = [
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'En mantenimiento',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },

  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },

  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
  {
    ip: '193.168.2',
    nombre: 'Projector 2',
    modelo: 'Model B',
    referencia: 'Ref002',
    horasLampara: 120,
    grupos: 'Group 1',
    etiquetas: ['tag1', 'tag2'],
    ubicacion: 'Room 2',
    estado: 'Apagado',
  },
  {
    ip: '193.168.3',
    nombre: 'Projector 3',
    modelo: 'Model C',
    referencia: 'Ref003',
    horasLampara: 300,
    grupos: 'Group 2',
    etiquetas: ['tag3'],
    ubicacion: 'Room 3',
    estado: 'Encendido',
  },
];

export function GET() {
  return Response.json(data);
}
